routes/web.php
<?php

use App\Http\Controllers\Account\SettingsController;
use App\Http\Controllers\Auth\SocialiteLoginController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\Documentation\ReferencesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\Logs\AuditLogsController;
use App\Http\Controllers\Logs\SystemLogsController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OfferController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\QuestionnaireController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return redirect('index');
});

$menu = theme()->getMenu();
array_walk($menu, function ($val) {
    if (isset($val['path'])) {
        $route = Route::get($val['path'], [PagesController::class, 'index']);

        // Exclude documentation from auth middleware
        if (!Str::contains($val['path'], 'documentation')) {
            $route->middleware('auth');
        }
    }
});

// Documentations pages
Route::prefix('documentation')->group(function () {
    Route::get('getting-started/references', [ReferencesController::class, 'index']);
    Route::get('getting-started/changelog', [PagesController::class, 'index']);
});

Route::middleware('auth')->group(function () {
    // Account pages
    Route::prefix('account')->group(function () {
        Route::get('settings', [SettingsController::class, 'index'])->name('settings.index');
        Route::put('settings', [SettingsController::class, 'update'])->name('settings.update');
        Route::put('settings/email', [SettingsController::class, 'changeEmail'])->name('settings.changeEmail');
        Route::put('settings/password', [SettingsController::class, 'changePassword'])->name('settings.changePassword');
    });
    // Logs pages
    Route::prefix('log')->name('log.')->group(function () {
        Route::resource('system', SystemLogsController::class)->only(['index', 'destroy']);
        Route::resource('audit', AuditLogsController::class)->only(['index', 'destroy']);
    });
    //Offer
    Route::get('/offer/index', [OfferController::class, 'index']);
    Route::post('/offer/form_modal/{offer?}', [OfferController::class, 'form_modal']);
    Route::post('/offer/store/{offer?}', [OfferController::class, 'store']);
    Route::post('/offer/delete/{offer?}', [OfferController::class, 'delete']);
    Route::get('/offer/data_list', [OfferController::class, 'data_list']);
    Route::get('/offer/detail/{offer?}', [OfferController::class, 'detail']);
    // Category
    Route::post('/category/modal_form/{offer?}/{category?}', [CategoryController::class, 'modal_form']);
    Route::post('/category/store/{offer?}/{category?}', [CategoryController::class, 'store']);
    Route::get('/category/data_list/{offer?}', [CategoryController::class, 'data_list']);
    Route::post('/category/delete/{category?}', [CategoryController::class, 'delete']);

    // Questionnaire
    Route::post('/questionnaire/list/{category?}', [QuestionnaireController::class, 'list']);
    Route::post('/questionnaire/modal_form/{category?}/{questionnaire?}', [QuestionnaireController::class, 'modal_form']);
    Route::post('/questionnaire/store/{category?}/{questionnaire?}', [QuestionnaireController::class, 'store']);
    Route::get('/questionnaire/data_list/{category?}', [QuestionnaireController::class, 'data_list']);
    Route::post('/questionnaire/delete/{questionnaire?}', [QuestionnaireController::class, 'delete']);

    // Questionnaire offer
    Route::post('/questionnaireOffer/form_modal/{offer?}/{questionnaire?}', [QuestionnaireController::class, 'modal_form_offer']);
    Route::get('/questionnaireOffer/data_list_offer/{offer?}', [QuestionnaireController::class, 'data_list_offer']);
    Route::post('/questionnaireOffer/storeOffer/{offer?}/{questionnaire?}', [QuestionnaireController::class, 'storeOffer']);
    Route::post('/questionnaireOffer/deleteOffer/{questionnaire?}', [QuestionnaireController::class, 'deleteOffer']);

    //'Questionnaire preliminary info question
    Route::get('/questionnaire/preliminary_info', [QuestionnaireController::class, 'preliminary_info']);
    Route::get('/questionnaire/preliminary_info/data_list', [QuestionnaireController::class, 'preliminary_info_data_list']);
    Route::post('/questionnaire/preliminary_info/store', [QuestionnaireController::class, 'storePreliminary']);
    Route::post('/questionnaire/preliminary/modal_form', [QuestionnaireController::class, 'preliminary_modal']);
    Route::post('/questionnaire/deletePreliminary/{questionnaire}', [QuestionnaireController::class, 'deletePreliminary']);
    /** Projects */
    Route::get('/project', [ProjectController::class, 'index']);
    Route::get('/project/list', [ProjectController::class, 'data_list']);
    Route::get('/project/detail/{project}', [ProjectController::class, 'detail']);
    Route::get('/project/files/list/{project}', [ProjectController::class, 'project_files']);
    Route::get('/project/file/download/{file}', [ProjectController::class, 'download']);
    Route::get('/project/tab/description/{project}', [ProjectController::class, 'tab_description']);
    Route::get('/project/download/file/{file}', [ProjectController::class, 'download_file']);
    Route::post('/project/save_step2/info_ground/save/{project}', [ProjectController::class, 'save_info_ground']);
    Route::post('/project/save_step2/responses_of_question/save/{project}', [ProjectController::class, 'save_responses_of_question']);
    Route::get('/project/kanban/index', [ProjectController::class, 'kanban']);
    Route::post('/kanban/data/source', [ProjectController::class, 'kanban_data']);

    /** Projects members */
    Route::get('/project_member/data_list_member', [ProjectController::class, 'data_list_member']);
    Route::post('/project_member/add_member_modal_form', [ProjectController::class, 'add_member_modal_form']);
    Route::post('/project_member/delete/', [ProjectController::class, 'delete_member']);
    Route::post('/project_member/assign/{project?}', [ProjectController::class, 'assign_member']);
    /** Relaunch project */
    Route::post('/project/relaunch/summary/{project}', [ProjectController::class, 'relaunch']);
    Route::post('/project/relaunch/add/{project}', [ProjectController::class, 'add_relaunch']);
    Route::post('/project/relaunch/add2/{project}', [ClientController::class, 'add_relaunch']);
    Route::post('/project/relaunch/mark/seen', [ClientController::class, 'mark_as_seen']);
    Route::get('/project/relaunch/list/{project}', [ProjectController::class, 'relaunch_list']);
    Route::post('/project/set/start', [ProjectController::class, 'set_start']);
    Route::post('/project/set/finish', [ProjectController::class, 'set_finish']);
    Route::post('/project/set/correction', [ProjectController::class, 'set_correction']);

    /** Add  estimate for project */
    Route::post('/project/estimate/form/{project}', [ProjectController::class, 'estimat_form']);
    Route::post('/project/estimate/add/{project}', [ProjectController::class, 'add_estimate']);
    /* Start a project */
    Route::post('/project/start/form/{project}', [ProjectController::class, 'start_form']);
    Route::post('/project/start/add/{project}', [ProjectController::class, 'add_start']);
    Route::post('/project/set_status/{project}', [ProjectController::class, 'set_status']);
    Route::post('/project/set_version/{project}', [ProjectController::class, 'set_version']);
    /** Users */
    Route::get('/users/list', [UsersController::class, 'index']);
    Route::get('/users/data_list', [UsersController::class, 'data_list']);
    Route::post('/users/form/user', [UsersController::class, 'form']);
    Route::post('/users/create/user', [UsersController::class, 'store']);
    Route::post('/send/email', [UsersController::class, 'send_email']);
    Route::post('/users/save/theme', [UsersController::class, 'save_theme_mode']);

    Route::group(['middleware' => ['auth'] ], function() {
         // Client projects
        Route::get('/client/project/index', [ClientController::class, 'projects']);
        Route::get('/client/project/list', [ClientController::class, 'data_list']);
        /** Estimate */
        Route::post('/estimate/validation/{project}', [ClientController::class, 'estimate_validation']);
        Route::post('/project/accept/estimate/{project}', [ClientController::class, 'accept_estimate']);
        Route::post('/project/refuse/estimate/{project}', [ClientController::class, 'refuse_estimate']);
        Route::post('/project/estimate/save_refuse/{project}', [ClientController::class, 'save_refuse_estimate']);
        //Project invoice
        Route::get('/project/invoice/preview/{invoice}', [InvoiceController::class, 'preview']);
        Route::get('/project/invoice/pdf/{invoice}', [InvoiceController::class, 'pdf']);
        Route::post('/project/invoice/checkout-form/{invoice}', [InvoiceController::class, 'checkout_form']);
        Route::post('/project/invoice/checkout/{invoice}', [InvoiceController::class, 'checkout']);
        Route::get('/project/invoice/download/{invoiceItem}', [InvoiceController::class, 'download_invoice']);
      });
    //Dashboard
    Route::get('dashboard/index', [DashboardController::class, 'index']);

    // settings

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Cashier\Billable;
use Spatie\Permission\Traits\HasRoles;
use App\Core\Traits\SpatieLogsActivity;
use Illuminate\Notifications\Notifiable;
use App\Notifications\ResetPasswordNotification;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Auth\Passwords\CanResetPassword as CanResetPasswords;


class User extends Authenticatable implements CanResetPassword
{
    use HasFactory, Notifiable , Billable, SpatieLogsActivity ,HasRoles ,CanResetPasswords;
    protected $guarded = [];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];
    // protected $appends  = [
    //     "message_not_seen"
    // ];
    protected static $logName = 'user';
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    protected $with = ["client", "type"];

    public function routeNotificationForNexmo($notification)
    {
        return $this->phone;
    }
    public function getNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
    public function getAvatarUrlAttribute()
    {
        if ($this->avatar) {
            return asset("avatars/".$this->avatar);
        }else{
            return "https://i.pravatar.cc/80?img={$this->id}";
            // return asset(theme()->getMediaUrlPath() . 'avatars/blank.png');
        }
    }
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPasswordNotification($token));
    }
    public function info()
    {
        return $this->hasOne(UserInfo::class);
    }
    public function projects()
    {
        return $this->belongsToMany(Project::class, "project_member");
    }
    public function type()
    {
        return $this->belongsTo(UserType::class, "user_type_id");
    }
    public function client()
    {
        return $this->hasOne(Client::class);
    }
    public function client_id()
    {
        if ($this->is_client()) {
            return $this->client->id;
        }
    }
    public function function()
    {
        return $this->type();
    }
    public function is_admin()
    {
        return $this->user_type_id == 1 ;
    }
    public function not_admin()
    {
        return !$this->is_admin();
    }
    public function is_client()
    {
        return $this->user_type_id == 5;
    }
    public function not_client()
    {
        return !$this->is_client();
    }
    public function is_mdp()
    {
        return $this->user_type_id == 2;
    }
    public function is_dessignator()
    {
        return $this->user_type_id == 4;
    }
    public function is_commercial()
    {
        return  $this->user_type_id == 3;
    }
    public function is_urba()
    {
        return  $this->user_type_id == 6;
    }
    public function getMessageNotSeenAttribute()
    {
        return $this->message_not_seen();
    }
    public function message_not_seen(){
        $me = auth()->id();
        return Message::select("id")
                    ->where('sender_id',$this->id )->where('receiver_id',$me)
                    ->whereRaw('NOT FIND_IN_SET('.$me.',deleted_by)')
                    ->whereRaw('NOT FIND_IN_SET('.$me.',seen_by)')
                    ->whereDeleted(0)
                    ->count();
    }
}

resources/views/project/detail/index.blade.php
<x-base-layout>
    <div class="card mb-6 mb-xl-9 shadow-sm col-md-12">
        <div class="card-header mt-5 ">
            @include('project.detail.state' , ["project" => $project ,"states" => $states])
        </div>
        <div class="card-body pt-9 pb-0">
            <div class="d-flex flex-wrap flex-sm-nowrap mb-6">
                <div class="flex-grow-1">
                    <div class="d-flex justify-content-between align-items-start flex-wrap mb-2">
                        <div class="d-flex flex-column">
                            <div class="d-flex align-items-center mb-1">
                                <a href="#"
                                    class="text-gray-800 text-hover-primary fs-2 fw-bolder me-3">{{ $project->client->user->name }}</a>
                                <span
                                    class="badge badge-light-{{ $project->status->class }} me-auto"> 
                                    @if ($project->estimate == "accepted" && $project->status->id == 3 && auth()->user()->is_client())
                                        Completion de dessies
                                    @else
                                        {{ trans("lang.{$project->status->name}") }}
                                    @endif    
                                </span>
                            </div>
                            <div class="d-flex flex-wrap fw-bold mb-4 fs-5 text-gray-400">
                                {{ $project->categories->pluck('name')->implode(',') }}</div>
                        </div>
                        <div class="d-flex mb-4">
                            @if (auth()->user()->is_client())
                                @if (!$project->estimate || $project->estimate =="refused")
                                    
                                    <a class="btn btn-sm  btn-light-primary me-3" data-project-id ={{ $project->id }}  id="accept_estimate">
                                        <span class="indicator-label" id="accpeted">
                                            J'accepte le devis.
                                        </span>
                                        <span class="indicator-progress">
                                            Un instant...
                                            <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
                                        </span>
                                    </a>
                                    @php
                                        echo modal_anchor(url("/project/refuse/estimate/$project->id"), 'Non, J\'accepte pas le devis', ['class' => 'btn btn-sm  btn-light me-3', 'title' => " "]);
                                    @endphp
                                @endif
                            @endif
                        </div>
                    </div>
                    <div class="d-flex flex-wrap justify-content-start">
                        <div class="d-flex flex-wrap">
                            @if ($project->accept_estimate == 'accepted')
                                <div
                                    class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                                    <div class="d-flex align-items-center">
                                        <div class="fs-4 fw-bolder text-primary">
                                            {{ $project->start_date ? $project->start_date->format('d-M-Y') : '-' }}
                                        </div>
                                    </div>
                                    <div class="fw-bold fs-6 text-gray-400 ">Debut date</div>
                                </div>
                                <div
                                    class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                                    <div class="d-flex align-items-center">
                                        <div class="fs-4 fw-bolder text-danger ">
                                            {{ $project->due_date ? $project->due_date->format('d-M-Y') : '-' }}
                                        </div>
                                    </div>
                                    <div class="fw-bold fs-6 text-gray-400  ">Date de livraivon</div>
                                </div>
                            @endif
                            <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                                <div class="d-flex align-items-center">
                                    <i class="fas fa-money-check-alt"></i> &nbsp;
                                    <div class="fs-4 fw-bolder text-primary" @if ($project->price) data-kt-countup="true" data-kt-countup-value="{{ $project->price }}" data-kt-countup-prefix="{{app_setting("currency_symbole")}}" @endif>
                                        {{format_to_currency( $project->price ? $project->price  : '0.000' )}}
                                    </div>
                                </div>
                                @if ($project->estimate == 'accepted')
                                    <div class="fw-bold fs-6  text-gray-400">{{ trans("lang.price") }} ( taxe : {{get_array_value($invoice_data,"taxe_percent")}}% )</div>
                                @endif
                            </div>
                            @if ($project->estimate == 'accepted')
                                <div
                                    class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                                    <div class="d-flex align-items-center">
                                        <i class="fas fa-money-check-alt"></i> &nbsp;
                                        <div class="fs-4 fw-bolder" data-kt-countup="true" data-kt-countup-prefix="{{app_setting("currency_symbole")}}">
                                            {{format_to_currency(get_array_value($invoice_data,"total_paid"))}}
                                        </div>
                                    </div>
                                    <div class="fw-bold fs-6 text-gray-400 ">{{ trans("lang.total_paid") }}</div>
                                </div>
                                <div
                                    class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-6 mb-3">
                                    <div class="d-flex align-items-center">
                                        <i class="fas fa-money-check-alt"></i> &nbsp;
                                        <div class="fs-4 fw-bolder  " data-kt-countup="true" data-kt-countup-prefix="{{app_setting("currency_symbole")}}">
                                            {{format_to_currency(get_array_value($invoice_data,"rest_to_paid"))}} 
                                        </div>
                                    </div>
                                    <div class="fw-bold fs-6 text-gray-400 ">{{ trans("lang.total_not_paid") }}</div>
                                </div>
                            @endif
                        </div>
                        @if (auth()->user()->not_client())
                        <div class="symbol-group symbol-hover mb-3">
                            @foreach ( get_cache_member($project) as $member)
                                <div class="symbol symbol-35px symbol-circle" data-bs-toggle="tooltip" title="" data-bs-original-title="{{$member->name}}">
                                    <img alt="Pic" src="{{ $member->avatar_url }}"> 
                                </div>
                            @endforeach
                        </div>
                    @endif
                    </div>
                </div>
            </div>
            <div class="separator"></div>
            <div class="d-flex overflow-auto h-55px">
                <ul
                    class="nav nav-stretch nav-line-tabs nav-line-tabs-2x border-transparent fs-5 fw-bolder flex-nowrap">
                    <li class="nav-item">
                        <a class="nav-link text-active-primary me-6 active" data-toggle="ajax-tab" data-bs-toggle="tab"
                            href="#descriptions"
                            data-loal-url="{{ url("/project/tab/description/$project->id") }}">Déscriptions</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-active-primary me-6" data-toggle="ajax-tab" data-bs-toggle="tab"
                            href="#files" data-loal-url="#">Fichiers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-active-primary me-6" data-toggle="ajax-tab" data-bs-toggle="tab"
                            href="#activity" data-loal-url="#">Activity</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-active-primary me-6" data-toggle="ajax-tab" data-bs-toggle="tab"
                            href="#invoices" data-loal-url="#">Facture et payment</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-active-primary me-6" data-toggle="ajax-tab" data-bs-toggle="tab"
                            href="#settings" data-loal-url="#">Settings</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row g-6 g-xl-9">
        <div class="tab-content" id="tab-project-details">
            <div class="tab-pane fade show active" id="descriptions" role="tabpanel"></div>
            <div class="tab-pane fade" id="files" role="tabpanel">files</div>
            <div class="tab-pane fade" id="activity" role="tabpanel">activity</div>
            <div class="tab-pane fade" id="invoices" role="tabpanel">invoices</div>
            <div class="tab-pane fade" id="settings" role="tabpanel">settings</div>
        </div>
    </div>
    @section('scripts')
        <script>
            $(document).ready(function() {
                $("#accept_estimate").on("click", function() {
                    var _this = $(this) 
                    _this.attr("data-kt-indicator", "on");
                    var projectId = _this.attr("data-project-id")
                    var uri = "{{ url('/project/accept/estimate') }}" +"/"+ projectId
                    $.ajax({
                        type: "POST",
                        data: { _token : getCsrfToken() },
                        url: uri,
                        success: function(response) {
                            _this.removeAttr("data-kt-indicator");
                            if (response.success) {
                                $("#accpeted").text(response.message)
                                toastr.success(response.message);
                                setTimeout(() => {
                                    window.location.replace(response.redirect);
                                }, 200);   
                            }else{
                                $("#accpeted").text(response.message)
                                toastr.success(response.message);
                            }
                        }
                    });
                })
            })
        </script>
    @endsection
</x-base-layout>

resources/views/project/detail/state.blade.php
<div class="stepper stepper-pills flex-column flex-xl-row flex-row-fluid mb-5" id="stepper-state" >
    <div class="stepper-nav ">
        @foreach ($states as $state)
            @php
                $is_current =  get_array_value($state, 'current'); 
                $is_completed =  get_array_value($state, 'completed'); 
            @endphp
            <div class="stepper-item {{ $is_current ? "current" : "" }}  {{ $is_completed ? "completed" : "" }} " data-kt-stepper-element="nav">
                <div class="stepper-line w-10px"></div>
                <div class="stepper-icon w-40px h-40px">
                    <i class="stepper-check fas fa-check "></i>
                    <span class="stepper-number ">{{ get_array_value($state,"step") }}</span>
                </div>
                <div class="stepper-label">
                    <h3 @if ($is_current) style="color: white !important" @endif class="stepper-title  {{  $is_completed ? "text-gray-400" : "text-gray-500" }}  " >  {{ get_array_value($state,"title") }}</h3>
                    <div class="stepper-desc  @if ($is_current) style="color: white !important" @endif ">{{ get_array_value($state,"desc") }}</div>
                </div>
            </div>
        @endforeach
    
         
    </div>
</div>